
[master]
name            = "LOS Fix"
tags            = ["Fix", "Balance", "Gameplay Modification"]
autodescription = true
description     = "README.md"
preview         = "preview.png"
website         = "https://github.com/Laaas/NS2FixedLOS/"

[beta]
name            = "LOS Fix - Beta"
tags            = ["Fix", "Balance", "Gameplay Modification"]
autodescription = false
description     = "description.beta.md"
preview         = "preview.png"
